#!/bin/bash

# Check if PYFILE is set
if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable not set."
    exit 1
fi

# Set the output filename
PYCFILE="${PYFILE%.py}.pyc"

# Compile the Python script
python3 -m compileall "$PYFILE"

# Check if compilation was successful
if [ $? -eq 0 ]; then
    echo "Compiling $PYFILE ..."
    mv "__pycache__/$PYCFILE" .
    rm -rf "__pycache__"
else
    echo "Error: Compilation failed for $PYFILE."
    exit 1
fi

